import type { Task } from "@/types/task";

export const sampleTasks: Task[] = [
  {
    id: "1",
    title: "Инсталирам VS Code, Node.js и Git",
    description: "Подготвям си средата за разработка. Инсталирам Visual Studio Code, Node.js (LTS версия) и Git. После проверявам дали всичко работи правилно, изпълнявайки базови команди в терминала.",
    status: "done",
    priority: "high",
  },
  {
    id: "2",
    title: "Запознавам се с Git основите",
    description: "Разучавам какво е Git, защо се използва, какво е repository, commit и branch. Целта е да придобия обща представа, не нужно да навлизам в дълбочина за сега.",
    status: "done",
    priority: "high",
  },
  {
    id: "3",
    title: "Изучавам React, Next.js и разликите",
    description: "Проучвам какво представлява React и Next.js, каква е разликата между тях, какво е App Router и какво представлява TypeScript. Разгледам официалната документация и други ресурси.",
    status: "done",
    priority: "high",
  },
  {
    id: "4",
    title: "Запознавам се с Tailwind CSS",
    description: "Разучавам какво е Tailwind CSS и как се използва за стилизиране. Целта е да разбера основния концепт преди да го прилагам в проекта.",
    status: "done",
    priority: "medium",
  },
  {
    id: "5",
    title: "Създавам нов Next.js проект",
    description: "Инициирам нов Next.js проект със TypeScript и Tailwind CSS. Пускам го локално и проверявам дали работи правилно на localhost.",
    status: "done",
    priority: "high",
  },
  {
    id: "6",
    title: "Разбирам структурата на проекта",
    description: "Разглеждам структурата на создадения проект. Изучавам предназначението на app/ папка, page.tsx, layout.tsx, globals.css, public/ папка и других компоненти.",
    status: "done",
    priority: "high",
  },
  {
    id: "7",
    title: "Разбирам npm и package.json",
    description: "Проучвам какво прави npm install, какво прави npm run dev, какво е package.json и как управлява зависимостите на проекта.",
    status: "done",
    priority: "medium",
  },
  {
    id: "8",
    title: "Променям началната страница",
    description: "Замествам стандартното съдържание със собствено. Добавям име на проекта (TaskFlow), кратко описание и бутон 'Get Started'.",
    status: "done",
    priority: "high",
  },
  {
    id: "9",
    title: "Създавам About страница",
    description: "Добавям нова страница '/about' използвайки App Router. На нея поставям информация за технологиите, които изучавам.",
    status: "done",
    priority: "medium",
  },
  {
    id: "10",
    title: "Добавям навигация между страниците",
    description: "Создавам меню с линкове между Home и About. Използвам App Router и Next.js Link компонент за навигация.",
    status: "done",
    priority: "high",
  },
  {
    id: "11",
    title: "Проектирам началната страница с Tailwind",
    description: "Преправям началната страница със собствен дизайн. Добавям Header, Hero секция, бутони и Footer, използвайки Tailwind CSS (Flexbox, Grid, Padding, Margin, Responsive класове).",
    status: "done",
    priority: "high",
  },
  {
    id: "12",
    title: "Прегледам целия проект и консолидирам",
    description: "Преглеждам целия проект от Седмица 1. Обяснявам какво е React, Next.js, App Router, TypeScript, Tailwind CSS. Направам малки подобрения, които видя.",
    status: "done",
    priority: "medium",
  },
  {
    id: "13",
    title: "Разбирам React компоненти и props",
    description: "Запознавам се с концепцията на React компоненти, какво са props, защо е добре интерфейсът да се разделя на по-малки преизползваеми части.",
    status: "done",
    priority: "high",
  },
  {
    id: "14",
    title: "Разделям началната страница на компоненти",
    description: "Преработвам началната страница, разделяйки я на отделни компоненти: Header, Hero, FeatureCard и Footer. Всеки компонент е в собствен файл в /components папка.",
    status: "done",
    priority: "high",
  },
  {
    id: "15",
    title: "Разбирам Next.js layouts",
    description: "Изучавам какво е layout в Next.js, къде се използва layout.tsx, каква е разликата между общ layout и отделна страница.",
    status: "done",
    priority: "medium",
  },
  {
    id: "16",
    title: "Създавам основния layout на приложението",
    description: "Правя основен layout, който включва Header, Sidebar меню и главна зона за съдържание. Добавям линкове към Dashboard, Tasks, Projects и Settings.",
    status: "done",
    priority: "high",
  },
  {
    id: "17",
    title: "Добавям примерни страници (Dashboard, Tasks, Projects, Settings)",
    description: "Създавам четирите примерни страници под главния layout. Засега те са с прост текст, целта е да работи маршрутизирането.",
    status: "done",
    priority: "medium",
  },
  {
    id: "18",
    title: "Разбирам TypeScript types и interfaces",
    description: "Запознавам се как се типизират props с TypeScript, какво е type и какво е interface, как да определя типа на данните за компонентите.",
    status: "done",
    priority: "high",
  },
  {
    id: "19",
    title: "Создавам TaskCard компонент с типове",
    description: "Правя компонент TaskCard, който показва заглавие, описание, статус (To do, In progress, Done) и приоритет (Low, Medium, High). Типизирам props с TypeScript.",
    status: "done",
    priority: "high",
  },
  {
    id: "20",
    title: "Разбирам .map() и списъци в React",
    description: "Запознавам се как работи .map() в JavaScript, как React показва списъци, защо се използва key свойството при рендериране на массиви.",
    status: "done",
    priority: "high",
  },
  {
    id: "21",
    title: "Создавам примерни задачи и Task List",
    description: "Правя масив с 8-10 примерни задачи, всяка със заглавие, описание, статус и приоритет. Показвам ги чрез TaskCard компонент с помощта на .map().",
    status: "done",
    priority: "high",
  },
  {
    id: "22",
    title: "Разбирам useState React Hook",
    description: "Запознавам се как работят формите в React, какво е useState, как се съхранява стойност от input поле и как се управлява състоянието на компонента.",
    status: "done",
    priority: "high",
  },
  {
    id: "23",
    title: "Создавам форма за добавяне на задача",
    description: "Правя форма със полета за заглавие, описание, статус и приоритет. Свързвам input полетата със state и проверявам дали работят правилно.",
    status: "done",
    priority: "high",
  },
  {
    id: "24",
    title: "Разбирам как се променя массив в React state",
    description: "Запознавам се как да променям масив в React state, какво е spread operator (...), как да обработвам форма с preventDefault() и как да предотвратявам презареждането на страницата.",
    status: "done",
    priority: "high",
  },
  {
    id: "25",
    title: "Свързвам формата със списъка на задачите",
    description: "Правя функционалност, при която формата добавя нова задача към списъка. Всяка задача получава уникално id, полетата се изчистват след submit, и не позволявам добавяне без заглавие.",
    status: "done",
    priority: "high",
  },
  {
    id: "26",
    title: "Разбирам .filter() и как да изтривам",
    description: "Запознавам се как работи .filter() в JavaScript, как да подам функция чрез props, как детелски компонент да изпрати действие към родителския компонент.",
    status: "done",
    priority: "high",
  },
  {
    id: "27",
    title: "Добавям функционалност за изтриване на задача",
    description: "Добавям бутон за изтриване към всеки TaskCard. При натискане задачата се премахва от списъка чрез .filter().",
    status: "done",
    priority: "high",
  },
  {
    id: "28",
    title: "Разбирам как се обновяват елементи в массив",
    description: "Запознавам се как да обновя конкретен елемент в масив, как да използвам .map() за промяна на данни и как работят event handler функциите.",
    status: "done",
    priority: "high",
  },
  {
    id: "29",
    title: "Добавям функция за промяна на статус",
    description: "Правя възможност статусът на задачата да се променя между To do, In progress и Done. Използвам select поле или друг подход, и статусът влияе визуално на картата.",
    status: "done",
    priority: "high",
  },
  {
    id: "30",
    title: "Разбирам редактирането на задачи",
    description: "Запознавам се какво е edit mode, как да попълня форма със съществуващи данни, как да обновя обект в масив и разликата между добавяне и редактиране.",
    status: "done",
    priority: "high",
  },
  {
    id: "31",
    title: "Добавям функционалност за редактиране на задача",
    description: "Правя възможност за редактиране на задачи - могат да се променят заглавие, описание, статус и приоритет. Ще използвам същата форма за редактиране или отделна.",
    status: "done",
    priority: "high",
  },
  {
    id: "32",
    title: "Разбирам филтриране на данни",
    description: "Запознавам се как да филтрирам данни в JavaScript, как да комбинирам useState, .filter() и .map(), как да покажа съобщение при празен списък.",
    status: "done",
    priority: "high",
  },
  {
    id: "33",
    title: "Добавям филтри по статус",
    description: "Правя филтри за всички задачи, To do, In progress и Done. При избран филтър списъкът се филтрира, а ако няма задачи, показвам подходящо съобщение.",
    status: "done",
    priority: "high",
  },
  {
    id: "34",
    title: "Добавям поле за търсене",
    description: "Правя функционалност за търсене по заглавие и описание на задача. Списъкът се филтрира в реално време, докато пиша.",
    status: "in-progress",
    priority: "medium",
  },
  {
    id: "35",
    title: "Добавям статистика на задачите",
    description: "Показвам брой на всички задачи, To do задачи, In progress задачи и Done задачи. Статистиката се обновява автоматично при добавяне/изтриване.",
    status: "in-progress",
    priority: "medium",
  },
  {
    id: "36",
    title: "Добавям потвърждение при изтриване",
    description: "Преди да се изтрие задача, показвам диалог или модален прозорец с вопроса 'Сигурен ли си?' за потвърждение.",
    status: "todo",
    priority: "low",
  },
  {
    id: "37",
    title: "Тестирам всички функции на Task Manager-а",
    description: "Проверявам дали работят: добавяне, изтриване, промяна на статус, редактиране, филтриране, търсене и статистика. Направам кратка демонстрация.",
    status: "todo",
    priority: "high",
  },
  {
    id: "38",
    title: "Разбирам какво е CRUD",
    description: "Проучвам какво означава CRUD - Create, Read, Update и Delete. Свързвам тези операции с функционалностите на Task Manager-а.",
    status: "done",
    priority: "high",
  },
  {
    id: "39",
    title: "Подготвям структурата за CRUD операции",
    description: "Преглеждам какви данни има една задача и какви функции ще са нужни за добавяне, показване, редактиране и изтриване на задачи.",
    status: "done",
    priority: "high",
  },
  {
    id: "40",
    title: "Добавям страница за детайли на задача",
    description: "Създавам динамичен route /tasks/[id], който показва подробна информация за избраната задача. Използвам useParams и проверявам дали задачата съществува.",
    status: "done",
    priority: "high",
  },
  {
    id: "41",
    title: "Добавям линк към детайлите на задача",
    description: "Добавям възможност от TaskCard да се отвори отделна страница с детайлите. Използвам Next.js Link вместо обикновен anchor таг.",
    status: "done",
    priority: "medium",
  },
  {
    id: "42",
    title: "Подобрявам обработката на грешки",
    description: "Проверявам какво се случва при невалиден id, празно заглавие или липсващи данни. Добавям подходящо съобщение и not-found страница.",
    status: "in-progress",
    priority: "high",
  },
  {
    id: "43",
    title: "Тествам целия CRUD flow",
    description: "Тествам добавяне, четене, редактиране и изтриване на задачи. Проверявам и динамичната страница, филтрите и търсенето след всяка промяна.",
    status: "todo",
    priority: "high",
  },
  {
    id: "44",
    title: "Запознавам се със Supabase",
    description: "Разглеждам какво е Supabase и как може да се използва като backend за проекта. Проучвам Database, API и как се създава нов проект.",
    status: "done",
    priority: "high",
  },
  {
    id: "45",
    title: "Създавам Supabase проект",
    description: "Правя нов проект в Supabase и разглеждам dashboard-а. Записвам нужните настройки, без да добавям secret ключове директно в кода.",
    status: "done",
    priority: "high",
  },
  {
    id: "46",
    title: "Създавам таблица за задачите",
    description: "Правя таблица tasks с колони за title, description, status и priority. Проверявам дали типовете и default стойностите са подходящи.",
    status: "done",
    priority: "high",
  },
  {
    id: "47",
    title: "Свързвам Next.js със Supabase",
    description: "Инсталирам нужния Supabase пакет и създавам client файл. Добавям променливи в .env.local и проверявам дали връзката работи локално.",
    status: "in-progress",
    priority: "high",
  },
  {
    id: "48",
    title: "Зареждам задачите от базата",
    description: "Заменям примерните данни с данни от Supabase. Правя заявка за четене на задачите и показвам loading и error състояние при нужда.",
    status: "todo",
    priority: "high",
  },
  {
    id: "49",
    title: "Записвам нова задача в Supabase",
    description: "Променям формата за добавяне, така че новата задача да се записва в таблицата. След успешно добавяне обновявам списъка на екрана.",
    status: "todo",
    priority: "high",
  },
  {
    id: "50",
    title: "Разбирам основите на Authentication",
    description: "Проучвам какво е authentication, каква е разликата между sign up и sign in и защо потребителите трябва да имат защитен достъп до данните си.",
    status: "done",
    priority: "high",
  },
  {
    id: "51",
    title: "Добавям страница за вход",
    description: "Създавам login страница с полета за email и password. Добавям валидация на полетата и показвам съобщение при неуспешен вход.",
    status: "in-progress",
    priority: "high",
  },
  {
    id: "52",
    title: "Добавям регистрация на потребител",
    description: "Правя форма за създаване на акаунт и я свързвам със Supabase Auth. Проверявам какво се случва при вече използван email.",
    status: "todo",
    priority: "high",
  },
  {
    id: "53",
    title: "Показвам различно меню за влезли потребители",
    description: "Проверявам текущата сесия и показвам подходяща навигация според това дали потребителят е влязъл. Добавям и бутон за изход.",
    status: "todo",
    priority: "medium",
  },
  {
    id: "54",
    title: "Защитавам достъпа до задачите",
    description: "Ограничавам страниците и операциите със задачи само за автентикирани потребители. Проверявам дали потребител без вход не може да вижда лични данни.",
    status: "todo",
    priority: "high",
  },
  {
    id: "55",
    title: "Тествам вход, регистрация и изход",
    description: "Проверявам целия authentication flow - регистрация, вход, изход, грешна парола и презареждане на страницата. Записвам какво трябва да се подобри.",
    status: "todo",
    priority: "high",
  },
];
